// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

/**
 * Content for recipe documents
 */
interface RecipeDocumentData {
  /**
   * image field in *recipe*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: recipe.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * category field in *recipe*
   *
   * - **Field Type**: Select
   * - **Placeholder**: 料理のカテゴリーを一つ選択
   * - **API ID Path**: recipe.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<'メインディッシュ' | 'サイド' | 'スープ'>

  /**
   * mainFood field in *recipe*
   *
   * - **Field Type**: Select
   * - **Placeholder**: メイン食材を一つ選択
   * - **API ID Path**: recipe.mainFood
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  mainFood: prismic.SelectField<'肉' | '魚' | '卵' | '野菜' | '米' | 'パスタ' | 'パン'>

  /**
   * description field in *recipe*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recipe.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * recipe document from Prismic
 *
 * - **API ID**: `recipe`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RecipeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<RecipeDocumentData>,
  'recipe',
  Lang
>

export type AllDocumentTypes = RecipeDocument

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type { RecipeDocument, RecipeDocumentData, AllDocumentTypes }
  }
}
